const actionTypes = {
  THEME_APP: 'THEME_APP',
  GET_HOME: 'GET_HOME',
  GET_SONG: 'GET_SONG',
  IS_PLAY: 'IS_PLAY',
  IS_OPEN_PLAYLIST_MUSIC: 'IS_OPEN_PLAYLIST_MUSIC',
  DATA_USER: 'DATA_USER',
  ADD_SUCCESS: 'ADD_SUCCESS',
  RANDOM_SONG: 'RANDOM_SONG',
  CURRENT_PLAYLIST: 'CURRENT_PLAYLIST',
  GET_ARTIST_INFO: 'GET_ARTIST_INFO',
  CHART_HOME: 'CHART_HOME',
  IS_OPEN_VIDEO: 'IS_OPEN_VIDEO',
};
export default actionTypes;
