export { default as Home } from './Home';
export { default as ZingChart } from './ZingChart';
export { default as LibraryMusic } from './LibraryMusic';
export { default as NewRelease } from './NewRelease';
export { default as Album } from './Album';
export { default as DetailsArtist } from './DetailsArtist';
export { default as NewMusic } from './NewMusic';
export { default as Top100 } from './Top100';
export { default as SearchPage } from './SearchPage';
